# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]]
then
	# Shell is non-interactive.  Be done now!
	return
fi

# overwrite duplicate history
HISTCONTROL=erasedups:ignorespace

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=2048
HISTFILESIZE=4096

if [[ -f ~/.bash_aliases ]]
then
    . ~/.bash_aliases
fi

if command -v tmux >/dev/null
then
	# (tmux has-session >/dev/null && tmux attach) || tmux new
	if tmux has-session >/dev/null
	then
		[[ -z $TMUX ]] && tmux attach -d
	else
		tmux new
	fi
fi

PS1="\e[31;1m\u\e[0m @ \e[33;1m\h\e[0m: \w\n∫ "

if command -v nvim >/dev/null
then
	export EDITOR=nvim
fi

[[ -f ~/.fzf.bash ]] && source ~/.fzf.bash
