# -*- sh -*-
# enable color support of ls and other handy aliases
if $OS_MAC
then
  alias ls="ls -G"
else
  alias ls='ls --color'
fi

alias ll='ls -AlF'
alias la='ls -A'
alias l1='ls -1'
alias l='ls -CF'

alias grep='grep --color=auto'
alias egrep='grep -E'

if [[ -n $OS ]] && [[ $OS = *Linux* ]]
then
  alias ++='sudo xbps-install '
  alias +u='sudo xbps-install -Su'
  alias +-='sudo xbps-remove '
  alias '?'='xbps-query -Rs '
  alias '??'='xbps-query '
fi

if $OS_MAC
then
  alias ++='brew install '
  alias +u='brew update '
  alias +-='brew uninstall '
  alias '?'='brew search '
fi

# if you need anything more than this better find an external tool(add a new line ;)
alias c.='cd ../'
alias c..='cd ../../'
alias c...='cd ../../../'


alias +r='chmod +r'
alias +w='chmod +w'
alias +x='chmod +x'
alias r-='chmod -r'
alias w-='chmod -w'
alias x-='chmod -x'

alias mkdir='mkdir -p'
if command -v ruby >/dev/null
then
  alias ruby='ruby -w'
  alias   rb='ruby'

  command -v bundle >/dev/null && alias bexec='bundle exec'
fi

if command -v julia >/dev/null
then
    alias jl="julia --depwarn=error"
fi

if command -v git >/dev/null
then
  alias gi='git init'
  alias gm='git checkout master'
  alias g='git'

  ## auto completion for aliases
  if [[ -n $OS ]] && [[ $OS = *Linux* ]]
  then
    git_completion_file="/usr/share/bash-completion/completions/git"
  else
    git_completion_file="/tmp/hopefully-non/existing-fil/e--and-directory/placeholder"
  fi

  if [[ -f "$git_completion_file" ]]
  then
    ## pollute the environment!!
    source "$git_completion_file"
    __git_complete g __git_main
  fi

  unset git_completion_file
fi

# tmp is where I scratch my itch
alias tmp="pushd ${TMPDIR:-/tmp}"
if command -v ffmpeg >/dev/null
then
  srec() {
    local out="${1:-/tmp/srec_${RANDOM}.webm}"
    local display="${DISPLAY:-:0.0}"
    ffmpeg -video_size 1920x1080 -framerate 25 -f x11grab -i "${display}" "$out" -crf 0 -preset ultrafast && echo ">> $out"
  }
fi

if command -v scrot >/dev/null
then
  scap() {
    out="${1:-scap.png}"
    scrot -d 2 -s "${TMPDIR:-/tmp}/${out}"
  }
fi


if (command -v mupdf && command -v zenity) >/dev/null
then
  mupdf() {
    elog=$(command mupdf "$@" 2>&1)
    local mupdf_ec=$?

    if [[ "$mupdf_ec" != "0" ]] && grep -i '^error: needs a password' <<<"$elog"
    then
      local pass=$(zenity --title="PDF Password" --password)
      command mupdf -p "$pass" "$@"
      mupdf_ec=$?
    else
      echo -e "$elog" >&2
    fi

    ## honor MuPDF exit status
    return $mupdf_ec
  }
alias mupdf-x11=mupdf
fi


if (command -v poly && command -v rlwrap) >/dev/null
then
  alias poly='rlwrap -pYellow poly'
fi


if [[ "nvim" = "$EDITOR" ]]
then
  # for ed in "vi" "vim" "nvi"
  # do
  #   alias $ed='nvim'
  # done
  alias vim='nvim'
fi

[[ -n $EDITOR ]] && {
  for rc in "vimrc" "bashrc" "irbrc"
  do
    alias $rc="$EDITOR $HOME/.${rc}"
  done
}

command -v ipython 2>/dev/null >&2 && alias py=ipython
command -v     mpv 2>/dev/null >&2 && alias play='mpv --volume=100 --no-video'
if command -v tmux 2>/dev/null >&2
then
  alias tt='tmux attach'
fi

if command -v brew >/dev/null
then
  alias b="brew"
  alias br='brew ruby'
  alias bi='brew irb'
  alias bu='brew up'
fi

if command -v patchelf >/dev/null
then
  alias pef='patchelf'
  alias pelf='patchelf'

  alias pefi='patchelf --print-interpreter'
  alias pelfi='patchelf --print-interpreter'

  alias pefr='patchelf --force-rpath --print-rpath'
  alias pelfr='patchelf --force-rpath --print-rpath'

  alias pefsi='patchelf --set-interpreter'
  alias pelfsi='patchelf --set-interpreter'

  alias pefsr='patchelf --force-rpath --set-rpath'
  alias pelfsr='patchelf --force-rpath --set-rpath'
fi

if command -v patchelf.rb >/dev/null
then
  alias prb='patchelf.rb'
  alias prbi='patchelf.rb --print-interpreter'
  alias prbr='patchelf.rb --force-rpath --print-runpath'

  alias prbsi='patchelf.rb --set-interpreter'
  alias prbsr='patchelf.rb --force-rpath --set-runpath'
fi

if command -v notes >/dev/null
then
  alias td='notes o today'
fi

if command -v gpg2 >/dev/null
then
  gpg() { gpg2 "$@"; }
fi

alias d6='echo $((RANDOM % 6))'
alias d12='echo $((RANDOM % 12))'
alias d20='echo $((RANDOM % 20))'

